// <auto-generated />
namespace BusinessDb.Cor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddExpensesOrderType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExpensesOrderType));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111322226_AddExpensesOrderType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
