// <auto-generated />
namespace BusinessDb.Cor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModiftyCustomer2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModiftyCustomer2));
        
        string IMigrationMetadata.Id
        {
            get { return "201608011237072_ModiftyCustomer2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target2"); }
        }
    }
}
