// <auto-generated />
namespace BusinessDb.Cor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modiftycustomer_kdls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modiftycustomer_kdls));
        
        string IMigrationMetadata.Id
        {
            get { return "201609220519403_modiftycustomer_kdls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
